# Generated by Django 5.1.15 on 2026-08-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_name', models.CharField(default='Arkadaşım', help_text='Doğum günü kutlanacak kişinin adı.', max_length=120, verbose_name='Arkadaşın Adı')),
                ('main_heading', models.CharField(default='İyi ki Doğdun! 🎉', help_text='Sayfanın en üstünde gösterilecek büyük başlık.', max_length=255, verbose_name='Ana Başlık')),
                ('celebration_message', models.TextField(default='Seninle geçirdiğimiz her an çok değerli. Nice mutlu yıllara!', help_text='Ana kutlama mesajı — birden fazla paragraf yazabilirsiniz.', verbose_name='Kutlama Mesajı')),
                ('background_music', models.FileField(blank=True, help_text='İsteğe bağlı — MP3 veya WAV dosyası yükleyin.', null=True, upload_to='music/', verbose_name='Arka Plan Müziği')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='MemoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Anı fotoğrafı — kare veya yatay formatta en iyi görünür.', upload_to='memories/', verbose_name='Fotoğraf')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Erişilebilirlik için kısa açıklama.', max_length=200, verbose_name='Alt Metin')),
                ('description', models.TextField(blank=True, default='', help_text='Bu anıyla ilgili kısa bir not veya hikaye.', verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, help_text='Düşük sayılar önce gösterilir.', verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Anı Fotoğrafı',
                'verbose_name_plural': 'Anı Fotoğrafları',
                'ordering': ['order', 'id'],
            },
        ),
    ]
