# Generated by Django 5.1.15 on 2026-08-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='Notu bırakan kişinin adı veya takma adı.', max_length=120, verbose_name='Gönderenin Adı')),
                ('message', models.TextField(help_text='Doğum günü sahibine özel bırakılan mesaj.', verbose_name='Mesaj / Not')),
                ('gift_type', models.CharField(choices=[('gold', 'Altın Kutu 🎁'), ('pink', 'Pembe Kalp Kutu 💖'), ('purple', 'Mor Yıldız Kutu ✨'), ('emerald', 'Zümrüt Sürpriz Kutu 🌿')], default='gold', max_length=50, verbose_name='Hediye Türü')),
                ('is_read', models.BooleanField(default=False, help_text='Doğum günü sahibi veya admin bu notu okuduysa işaretleyin.', verbose_name='Okundu mu?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bırakılma Tarihi')),
            ],
            options={
                'verbose_name': 'Hediye Notu',
                'verbose_name_plural': 'Bırakılan Hediye Notları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='birthdaypageconfig',
            name='birth_date',
            field=models.DateTimeField(blank=True, help_text='Canlı sayaç için doğum tarihi ve saatini belirleyin (İsteğe bağlı).', null=True, verbose_name='Doğum Tarihi ve Saati'),
        ),
    ]
