# Generated by Django 5.1.15 on 2026-09-24 19:01

from django.db import migrations, models


def translate_existing_content(apps, schema_editor):
    BirthdayPageConfig = apps.get_model('birthday', 'BirthdayPageConfig')
    GiftNote = apps.get_model('birthday', 'GiftNote')

    BirthdayPageConfig.objects.filter(friends_name='Arkadaşım').update(
        friends_name='Mein Schatz',
        main_heading='Alles Gute zum Geburtstag! 🎉',
        celebration_message='Jeder Moment mit dir ist kostbar. Auf viele glückliche Jahre!',
    )
    GiftNote.objects.filter(sender_name='Test Arkadas', message='Iyi ki dogdun!').update(
        sender_name='Testfreund',
        message='Alles Gute zum Geburtstag!',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_giftnote_birthdaypageconfig_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthdaypageconfig',
            options={'verbose_name': 'Seiteneinstellungen', 'verbose_name_plural': 'Seiteneinstellungen'},
        ),
        migrations.AlterModelOptions(
            name='giftnote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Geschenknachricht', 'verbose_name_plural': 'Hinterlassene Geschenknachrichten'},
        ),
        migrations.AlterModelOptions(
            name='memoryphoto',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Erinnerungsfoto', 'verbose_name_plural': 'Erinnerungsfotos'},
        ),
        migrations.AlterField(
            model_name='birthdaypageconfig',
            name='background_music',
            field=models.FileField(blank=True, help_text='Optional; lade eine MP3- oder WAV-Datei hoch.', null=True, upload_to='music/', verbose_name='Hintergrundmusik'),
        ),
        migrations.AlterField(
            model_name='birthdaypageconfig',
            name='birth_date',
            field=models.DateTimeField(blank=True, help_text='Geburtsdatum und -zeit für den Live-Zähler (optional).', null=True, verbose_name='Geburtsdatum und -zeit'),
        ),
        migrations.AlterField(
            model_name='birthdaypageconfig',
            name='celebration_message',
            field=models.TextField(default='Jeder Moment mit dir ist kostbar. Auf viele glückliche Jahre!', help_text='Haupttext der Feier; du kannst mehrere Absätze schreiben.', verbose_name='Glückwunschtext'),
        ),
        migrations.AlterField(
            model_name='birthdaypageconfig',
            name='friends_name',
            field=models.CharField(default='Mein Schatz', help_text='Name der Person, deren Geburtstag gefeiert wird.', max_length=120, verbose_name='Name der geehrten Person'),
        ),
        migrations.AlterField(
            model_name='birthdaypageconfig',
            name='main_heading',
            field=models.CharField(default='Alles Gute zum Geburtstag! 🎉', help_text='Große Überschrift am oberen Rand der Seite.', max_length=255, verbose_name='Hauptüberschrift'),
        ),
        migrations.AlterField(
            model_name='giftnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hinterlassen am'),
        ),
        migrations.AlterField(
            model_name='giftnote',
            name='gift_type',
            field=models.CharField(choices=[('gold', 'Goldene Box 🎁'), ('pink', 'Rosa Herzbox 💖'), ('purple', 'Violette Sternenbox ✨'), ('emerald', 'Smaragdgrüne Überraschungsbox 🌿')], default='gold', max_length=50, verbose_name='Geschenktyp'),
        ),
        migrations.AlterField(
            model_name='giftnote',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Aktivieren, wenn das Geburtstagskind oder die Administration die Nachricht gelesen hat.', verbose_name='Gelesen?'),
        ),
        migrations.AlterField(
            model_name='giftnote',
            name='message',
            field=models.TextField(help_text='Persönliche Nachricht für das Geburtstagskind.', verbose_name='Nachricht / Notiz'),
        ),
        migrations.AlterField(
            model_name='giftnote',
            name='sender_name',
            field=models.CharField(help_text='Name oder Spitzname der Person, die die Nachricht hinterlässt.', max_length=120, verbose_name='Name des Absenders'),
        ),
        migrations.AlterField(
            model_name='memoryphoto',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Kurze Beschreibung für die Barrierefreiheit.', max_length=200, verbose_name='Alternativtext'),
        ),
        migrations.AlterField(
            model_name='memoryphoto',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Kurze Notiz oder Geschichte zu dieser Erinnerung.', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='memoryphoto',
            name='image',
            field=models.ImageField(help_text='Erinnerungsfoto; quadratisch oder im Querformat sieht es am besten aus.', upload_to='memories/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='memoryphoto',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Niedrigere Zahlen werden zuerst angezeigt.', verbose_name='Reihenfolge'),
        ),
        migrations.RunPython(translate_existing_content, migrations.RunPython.noop),
    ]
